/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlVisibleWidgetTemplate: typeof import('./src/components/ControlVisibleWidgetTemplate.vue')['default']
    FlashCardPanel: typeof import('./src/components/FlashCardPanel/index.vue')['default']
    ModalContainer: typeof import('./src/components/ModalContainer/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TransitionSlide: typeof import('./src/components/TransitionSlide.vue')['default']
    WidgetBackPanel: typeof import('./src/components/WidgetBackPanel.vue')['default']
    WidgetMenuBar: typeof import('./src/components/WidgetMenuBar/index.vue')['default']
  }
}
