/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const MessageNotify: typeof import('../src/utils/MessageNotify').default
  const MessgeNotify: typeof import('../src/utils/MessageNotify').MessgeNotify
  const __APP_INFO__: typeof import('../src/utils/sysTool').__APP_INFO__
  const aboutus_icon: typeof import('../src/utils/imageResource')['aboutus_icon']
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const appStore: typeof import('../src/stores/modules/appStore').appStore
  const asyncRouteStore: typeof import('../src/stores/modules/asyncRoute').asyncRouteStore
  const book_icon: typeof import('../src/utils/imageResource')['book_icon']
  const createPinia: typeof import('pinia').createPinia
  const deepMerge: typeof import('../src/stores/modules/appStore')['deepMerge']
  const defineStore: typeof import('pinia').defineStore
  const findMenuConfig: typeof import('../src/utils/WidgetUtils').findMenuConfig
  const findMenuItem: typeof import('../src/utils/WidgetUtils').findMenuItem
  const getActivePinia: typeof import('pinia').getActivePinia
  const getRightURL: typeof import('../src/utils/sysTool').getRightURL
  const getSystemID: typeof import('../src/utils/sysTool').getSystemID
  const getSystemPKG: typeof import('../src/utils/sysTool')['getSystemPKG']
  const guanneihuodong_icon: typeof import('../src/utils/imageResource')['guanneihuodong_icon']
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const message: typeof import('../src/utils/MessageNotify').message
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const questionnaire_icon: typeof import('../src/utils/imageResource')['questionnaire_icon']
  const set: typeof import('../src/utils/sysTool')['set']
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setN: typeof import('../src/utils/sysTool')['setN']
  const setupStore: typeof import('../src/stores/index').setupStore
  const showToast: typeof import('@tarojs/taro').showToast
  const storeToRefs: typeof import('pinia').storeToRefs
  const stores: typeof import('../src/stores/index').default
  const useLink: typeof import('vue-router').useLink
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const userStore: typeof import('../src/stores/modules/userStore').userStore
  const wenchuang_icon: typeof import('../src/utils/imageResource')['wenchuang_icon']
  const workerTool: typeof import('../src/utils/workerTool')['default']
  const yunwen_left: typeof import('../src/utils/imageResource')['yunwen_left']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MessgeNotify } from '../src/utils/MessageNotify'
  import('../src/utils/MessageNotify')
}
