/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleComponent: typeof import('./../src/components/ArticleComponent.vue')['default']
    AudioPlayer: typeof import('./../src/components/AudioPlayer.vue')['default']
    ControlVisibleWidgetTemplate: typeof import('./../src/components/ControlVisibleWidgetTemplate.vue')['default']
    FlashCardPanel: typeof import('./../src/components/FlashCardPanel/index.vue')['default']
    ModalContainer: typeof import('./../src/components/ModalContainer/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendarCard: typeof import('@nutui/nutui-taro')['CalendarCard']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    PrivateContract: typeof import('./../src/components/privateContract.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePagePanel: typeof import('./../src/components/SinglePagePanel.vue')['default']
    SwipeUpdown: typeof import('./../src/components/SwipeUpdown.vue')['default']
    TopNaviBar: typeof import('./../src/components/TopNaviBar.vue')['default']
    TransitionSlide: typeof import('./../src/components/TransitionSlide.vue')['default']
    WidgetBackPanel: typeof import('./../src/components/WidgetBackPanel.vue')['default']
    WidgetMenuBar: typeof import('./../src/components/WidgetMenuBar/index.vue')['default']
  }
}
